from Car import Car
from ParkingArea import ParkingArea
from ParkingService import ParkingService
import time

parking_area = ParkingArea()
parking_service = ParkingService(parking_area)
car_1 = Car("F 1111 X")
car_2 = Car("F 1211 X")
car_3 = Car("F 1311 X")
car_4 = Car("F 1411 X")
car_5 = Car("F 1511 X")
car_6 = Car("F 1611 X")
car_7 = Car("F 1171 X")
car_8 = Car("F 1121 X")
car_9 = Car("F 1131 X")
car_10 = Car("F 1161 X")
car_11 = Car("F 1191 X")

parking_service.car_in(car_1)
parking_service.car_in(car_2)
parking_service.car_in(car_3)
parking_service.car_in(car_4)
parking_service.car_in(car_5)
parking_service.car_in(car_6)
parking_service.car_in(car_7)
parking_service.car_in(car_8)
parking_service.car_in(car_9)
parking_service.car_in(car_10)
parking_service.car_in(car_11)

time.sleep(11)
parking_service.car_out(car_1)
time.sleep(9)
parking_service.car_out(car_2)
parking_service.car_out(car_3)
parking_service.car_out(car_4)
parking_service.car_out(car_5)
parking_service.car_out(car_6)
parking_service.car_out(car_7)
parking_service.car_out(car_8)
parking_service.car_out(car_9)
parking_service.car_out(car_10)
parking_service.car_in(car_11)