import turtle

turtle.penup()
turtle.goto(-160,110)

turtle.pendown()
turtle.color('blue')
turtle.begin_fill()

# membuat huruf C
turtle.forward(160)
turtle.right(90)
turtle.forward(40)
turtle.right(90)
turtle.forward(120)
turtle.left(90)
turtle.forward(120)
turtle.left(90)
turtle.forward(120)
turtle.right(90)
turtle.forward(40)
turtle.right(90)
turtle.forward(160)
turtle.right(90)
turtle.forward(200)

turtle.end_fill()

turtle.penup()
turtle.right(90)
turtle.forward(180)

turtle.pendown()
turtle.color('red')
turtle.begin_fill()

# membuat huruf S
turtle.forward(160)
turtle.right(90)
turtle.forward(40)
turtle.right(90)
turtle.forward(120)
turtle.left(90)
turtle.forward(40)
turtle.left(90)
turtle.forward(120)
turtle.right(90)
turtle.forward(120)
turtle.right(90)
turtle.forward(160)
turtle.right(90)
turtle.forward(40)
turtle.right(90)
turtle.forward(120)
turtle.left(90)
turtle.forward(40)
turtle.left(90)
turtle.forward(120)
turtle.right(90)
turtle.forward(120)

turtle.end_fill()

turtle.hideturtle()
turtle.exitonclick()
